import re
import pandas as pd

def clean_code(code_string):
    """Strips markdown code blocks from the AI's response."""
    # Find everything between ```python and ```
    match = re.search(r"```[a-zA-Z]*\n(.*?)\n```", code_string, re.DOTALL)
    if match:
        return match.group(1).strip()
    return code_string.strip()

def execute_code(code_string, df):
    """
    Executes the generated Python code safely and extracts the 'result' variable.
    
    Args:
        code_string (str): The Python/pandas code generated by the AI (must be clean).
        df (pd.DataFrame): The pandas DataFrame context.
        
    Returns:
        The value of the 'result' variable, or an error message.
    """
    # Create a local dictionary context for exec() to use and modify
    # We pass in `df` so the code can access it, and `pd` just in case.
    local_env = {"df": df, "pd": pd}
    
    try:
        # Execute the string as Python code
        # global context is empty {}, local context is local_env
        exec(code_string, {}, local_env)
        
        # Extract and return the variable specifically named 'result'
        if "result" in local_env:
            return local_env["result"]
        else:
            return "Error: The AI code did not define a 'result' variable."
            
    except Exception as e:
        return f"Execution Error: {str(e)}"
